# Generated by Django 4.1 on 2023-03-22 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/banners', verbose_name='фото')),
                ('banner_url', models.URLField(blank=True, max_length=255, verbose_name='URL банера')),
            ],
            options={
                'verbose_name': 'фоновий банер',
                'verbose_name_plural': 'фоновий банер',
            },
        ),
        migrations.CreateModel(
            name='FooterBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='розмір фото 1146х240', upload_to='photos/banners', verbose_name='фото')),
                ('banner_url', models.URLField(max_length=255, verbose_name='URL банера')),
            ],
            options={
                'verbose_name': 'банер',
                'verbose_name_plural': 'футер банер',
            },
        ),
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='заголовок')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='опис')),
                ('image', models.ImageField(upload_to='photos/banners', verbose_name='фото')),
                ('banner_url', models.URLField(max_length=255, verbose_name='URL банера')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='дата створення')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='дата коригування')),
            ],
            options={
                'verbose_name': 'головний банер',
                'verbose_name_plural': 'головні банери',
                'ordering': ('-modified_date',),
            },
        ),
        migrations.CreateModel(
            name='OfferSingleBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/banners', verbose_name='фото')),
                ('banner_url', models.URLField(max_length=255, verbose_name='URL банера')),
            ],
            options={
                'verbose_name': 'банер',
                'verbose_name_plural': 'банер (1од.)',
            },
        ),
        migrations.CreateModel(
            name='TwoBanners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='заголовок')),
                ('image', models.ImageField(help_text='розмір фото 561х190', upload_to='photos/banners', verbose_name='фото')),
                ('banner_url', models.URLField(max_length=255, verbose_name='URL банера')),
            ],
            options={
                'verbose_name': 'банер',
                'verbose_name_plural': 'банери (2од.)',
            },
        ),
        migrations.CreateModel(
            name='WeekOfferBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='назва банера')),
                ('image_active', models.ImageField(upload_to='photos/banners', verbose_name='фото 1 (активне)')),
                ('image', models.ImageField(upload_to='photos/banners', verbose_name='фото 2')),
                ('countdown', models.DateField(blank=True, null=True, verbose_name='таймер')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'пропозицію тижня',
                'verbose_name_plural': 'пропозиції тижня',
            },
        ),
    ]
