# Generated by Django 4.1 on 2023-03-06 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_options_alter_productgallery_options_and_more'),
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='заголовок')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='опис')),
                ('image', models.ImageField(upload_to='photos/banners', verbose_name='фото')),
                ('banner_url', models.URLField(max_length=255, verbose_name='URL банера')),
            ],
            options={
                'verbose_name': 'головний банер',
            },
        ),
        migrations.AlterModelOptions(
            name='weekofferbanner',
            options={'verbose_name_plural': 'пропозиції тижня'},
        ),
        migrations.AlterField(
            model_name='weekofferbanner',
            name='image',
            field=models.ImageField(upload_to='photos/banners', verbose_name='фото 2'),
        ),
        migrations.AlterField(
            model_name='weekofferbanner',
            name='image_active',
            field=models.ImageField(upload_to='photos/banners', verbose_name='фото 1 (активне)'),
        ),
        migrations.AlterField(
            model_name='weekofferbanner',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='weekofferbanner',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='назва банера'),
        ),
    ]
