# Generated by Django 4.1 on 2023-03-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_twobanners_alter_mainbanner_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferSingleBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/banners', verbose_name='фото')),
                ('banner_url', models.URLField(max_length=255, verbose_name='URL банера')),
            ],
            options={
                'verbose_name': 'банер',
                'verbose_name_plural': 'банер (1од.)',
            },
        ),
        migrations.AlterModelOptions(
            name='twobanners',
            options={'verbose_name': 'банер', 'verbose_name_plural': 'банери (2од.)'},
        ),
    ]
