# Generated by Django 4.1 on 2023-03-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_offersinglebanner_alter_twobanners_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/banners', verbose_name='фото')),
                ('banner_url', models.URLField(max_length=255, verbose_name='URL банера')),
            ],
            options={
                'verbose_name': 'банер',
                'verbose_name_plural': 'footer банер',
            },
        ),
    ]
