# Generated by Django 4.1 on 2023-03-06 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0005_footerbanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerbanner',
            options={'verbose_name': 'банер', 'verbose_name_plural': 'футер банер'},
        ),
    ]
