# Generated by Django 4.1 on 2023-03-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0006_alter_footerbanner_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekofferbanner',
            name='countdown',
            field=models.DateField(blank=True, null=True, verbose_name='таймер'),
        ),
    ]
