# Generated by Django 4.1 on 2023-03-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0007_weekofferbanner_countdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/banners', verbose_name='фото')),
                ('banner_url', models.URLField(blank=True, max_length=255, verbose_name='URL банера')),
            ],
            options={
                'verbose_name': 'фоновий банер',
                'verbose_name_plural': 'фоновий банер',
            },
        ),
    ]
