# Generated by Django 4.1 on 2023-03-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0008_backgroundbanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainbanner',
            options={'ordering': ('-modified_date',), 'verbose_name': 'головний банер', 'verbose_name_plural': 'головні банери'},
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='дата створення'),
        ),
        migrations.AddField(
            model_name='mainbanner',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='дата коригування'),
        ),
    ]
