# Generated by Django 4.1 on 2023-03-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0009_alter_mainbanner_options_mainbanner_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbanner',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата створення'),
        ),
    ]
