# Generated by Django 4.1 on 2023-03-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0010_alter_mainbanner_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbanner',
            name='image',
            field=models.ImageField(help_text='розмір фото 1146х240', upload_to='photos/banners', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='twobanners',
            name='image',
            field=models.ImageField(help_text='розмір фото 561х190', upload_to='photos/banners', verbose_name='фото'),
        ),
    ]
