# Generated by Django 4.1 on 2023-03-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0011_alter_mainbanner_image_alter_twobanners_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerbanner',
            name='image',
            field=models.ImageField(help_text='розмір фото 1146х240', upload_to='photos/banners', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='mainbanner',
            name='image',
            field=models.ImageField(upload_to='photos/banners', verbose_name='фото'),
        ),
    ]
