# Generated by Django 4.1 on 2023-03-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_salepoint_options_alter_salepoint_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salepoint',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='місто'),
        ),
        migrations.AlterField(
            model_name='salepoint',
            name='city_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='міський телефон'),
        ),
        migrations.AlterField(
            model_name='salepoint',
            name='corpus',
            field=models.CharField(blank=True, max_length=10, verbose_name='корпус'),
        ),
        migrations.AlterField(
            model_name='salepoint',
            name='description',
            field=models.TextField(blank=True, verbose_name='опис'),
        ),
        migrations.AlterField(
            model_name='salepoint',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='salepoint',
            name='house',
            field=models.CharField(blank=True, max_length=10, verbose_name='будинок'),
        ),
        migrations.AlterField(
            model_name='salepoint',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/sale_points', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='salepoint',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='salepoint',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, verbose_name='довгота'),
        ),
        migrations.AlterField(
            model_name='salepoint',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='мобільний телефон'),
        ),
        migrations.AlterField(
            model_name='salepoint',
            name='schedule',
            field=models.CharField(blank=True, max_length=200, verbose_name='графік роботи'),
        ),
        migrations.AlterField(
            model_name='salepoint',
            name='street',
            field=models.CharField(blank=True, max_length=100, verbose_name='вулиця'),
        ),
    ]
