# Generated by Django 4.1 on 2023-02-22 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Найменування товару')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('price', models.IntegerField(verbose_name='Ціна')),
                ('price_old', models.IntegerField(blank=True, null=True, verbose_name='Стара ціна')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Вага, кг')),
                ('product_image', models.ImageField(upload_to='photos/products', verbose_name='Фото товару')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступний')),
                ('is_new', models.BooleanField(default=False, verbose_name='New')),
                ('is_sale', models.BooleanField(default=False, verbose_name='Sale')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Дата змін')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='category.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ('-created_date',),
            },
        ),
    ]
