# Generated by Django 4.1 on 2023-03-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinfo',
            options={'verbose_name': 'інфо про товар', 'verbose_name_plural': 'інфо'},
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='description',
            field=models.TextField(blank=True, verbose_name='інфо'),
        ),
    ]
