# Generated by Django 4.1 on 2023-03-02 07:22

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgallery',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
