# Generated by Django 4.1 on 2023-03-02 07:40

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productgallery_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to='photos/gallery', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, help_text='Завантаж URL відео з YouTube', verbose_name='Відео'),
        ),
    ]
