# Generated by Django 4.1 on 2023-03-06 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_options_alter_productgallery_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='супутній товар')),
            ],
            options={
                'verbose_name': 'супутній товар',
                'verbose_name_plural': 'супутні товари',
            },
        ),
    ]
