# Generated by Django 4.1 on 2023-03-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_relatedproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='store.product'),
        ),
        migrations.DeleteModel(
            name='RelatedProducts',
        ),
    ]
