# Generated by Django 4.1 on 2023-03-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_related_products_delete_relatedproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='products', to='store.product', verbose_name='супутні товари'),
        ),
    ]
