# Generated by Django 4.1 on 2023-03-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_second_image_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_products_title',
            field=models.CharField(blank='З цим товаром купують', max_length=255, verbose_name='заголовок до супутніх товарів'),
        ),
    ]
