# Generated by Django 4.1 on 2023-03-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_related_products_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='инфо')),
            ],
            options={
                'verbose_name': 'инфо про товар',
                'verbose_name_plural': 'инфо',
            },
        ),
    ]
