# Generated by Django 4.1 on 2023-03-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='грн/шт', max_length=50, verbose_name='одиниця виміру'),
        ),
    ]
