# Generated by Django 4.1 on 2023-03-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='заповнюється автоматично, коли вносишь назву', max_length=255, unique=True, verbose_name='написання в URL'),
        ),
    ]
