# Generated by Django 4.1 on 2023-03-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_product_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'галерея товарів'},
        ),
    ]
