# Generated by Django 4.1 on 2023-03-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_reviewrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='rating',
            field=models.FloatField(default=0, verbose_name='рейтинг'),
        ),
    ]
