# Generated by Django 4.1 on 2023-03-13 12:22

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_reviewrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='rating',
            field=models.FloatField(validators=[store.models.validate_rating], verbose_name='рейтинг'),
        ),
    ]
