# Generated by Django 4.1 on 2023-03-15 17:22

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_reviewrating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0, validators=[store.models.validate_rating], verbose_name='рейтинг'),
        ),
    ]
