# Generated by Django 4.1 on 2023-03-15 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
