# Generated by Django 4.1 on 2023-03-15 17:41

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(validators=[store.models.validate_rating], verbose_name='рейтинг'),
        ),
    ]
