# Generated by Django 4.1 on 2023-02-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_kod', models.CharField(max_length=15, verbose_name='Промокод')),
                ('discount', models.PositiveSmallIntegerField(verbose_name='Знижка, %')),
                ('validity', models.DateField(verbose_name='Термін дії')),
                ('is_available', models.BooleanField(default=True, verbose_name='Знижка доступна')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Опис')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Дата змін')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоди',
                'ordering': ('-created_date',),
            },
        ),
    ]
