# Generated by Django 4.1 on 2023-03-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_kod', models.CharField(max_length=15, verbose_name='промокод')),
                ('discount', models.PositiveSmallIntegerField(verbose_name='знижка, %')),
                ('validity', models.DateField(verbose_name='термін дії')),
                ('is_available', models.BooleanField(default=True, verbose_name='знижка доступна')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='опис')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='дата створення')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='дата змін')),
            ],
            options={
                'verbose_name': 'промокод',
                'verbose_name_plural': 'промокоди',
                'ordering': ('-created_date',),
            },
        ),
    ]
