# Generated by Django 4.1 on 2023-03-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ('-created_date',), 'verbose_name': 'промокод', 'verbose_name_plural': 'промокоди'},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_kod',
            field=models.CharField(max_length=15, verbose_name='промокод'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата створення'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='опис'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.PositiveSmallIntegerField(verbose_name='знижка, %'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='знижка доступна'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='дата змін'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='validity',
            field=models.DateField(verbose_name='термін дії'),
        ),
    ]
