# Generated by Django 4.1 on 2023-03-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True, verbose_name='найменування категорії')),
                ('slug', models.SlugField(help_text='заповнюється автоматично, коли вносишь назву', max_length=255, unique=True, verbose_name='написання в URL')),
                ('description', models.TextField(blank=True, verbose_name='опис')),
                ('category_image', models.ImageField(blank=True, upload_to='photos/categories', verbose_name='фото категорії')),
            ],
            options={
                'verbose_name': 'категорію',
                'verbose_name_plural': 'категорії',
            },
        ),
    ]
