# Generated by Django 4.1 on 2023-02-22 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True, verbose_name='Найменування категорії')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('category_image', models.ImageField(blank=True, upload_to='photos/blog', verbose_name='Фото категорії')),
            ],
            options={
                'verbose_name': 'Категорію',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва тегу')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тема поста')),
                ('description', models.TextField(blank=True, verbose_name='Опис поста')),
                ('quote', models.TextField(blank=True, verbose_name='Цитата до посту')),
                ('post_image', models.ImageField(blank=True, upload_to='photos/blog/images', verbose_name='Фото до посту')),
                ('mini_image', models.ImageField(upload_to='photos/blog/mini_images', verbose_name='Міні фото до посту')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступний')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Дата змін')),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='blog.blogcategory', verbose_name='Категорія')),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Пости',
                'ordering': ('-created_date',),
            },
        ),
    ]
