# Generated by Django 4.1 on 2023-03-22 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True, verbose_name='найменування категорії')),
                ('slug', models.SlugField(help_text='заповнюється автоматично, коли вносишь назву', max_length=100, unique=True, verbose_name='написання в URL')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('category_image', models.ImageField(blank=True, upload_to='photos/blog', verbose_name='фото категорії')),
            ],
            options={
                'verbose_name': 'категорію',
                'verbose_name_plural': 'категорії',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='тема поста')),
                ('description', models.TextField(blank=True, verbose_name='опис поста')),
                ('quote', models.TextField(blank=True, verbose_name='цитата до посту')),
                ('post_image', models.ImageField(blank=True, upload_to='photos/blog/images', verbose_name='фото до посту')),
                ('mini_image', models.ImageField(upload_to='photos/blog/mini_images', verbose_name='міні фото до посту')),
                ('banner_url', models.URLField(blank=True, help_text='Введіть URL куди переходити по кліку на головне фото поста', max_length=255, verbose_name='URL переходу')),
                ('is_available', models.BooleanField(default=True, verbose_name='доступний')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='дата створення')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='дата змін')),
                ('related_posts_title', models.CharField(blank='Схожі пости', max_length=255, verbose_name='заголовок до схожих постів')),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='blog.blogcategory', verbose_name='категорія')),
                ('related_posts', models.ManyToManyField(blank=True, related_name='+', to='blog.post', verbose_name='схожі пости')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'пости',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='назва тегу')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name="ім'я")),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('content', models.TextField(verbose_name='коментар')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='дата створення')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='дата коригування')),
                ('is_moderated', models.BooleanField(default=False, verbose_name='промодерований')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='пост')),
            ],
            options={
                'verbose_name': 'коментар',
                'verbose_name_plural': 'коментари',
                'ordering': ('-modified_date',),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.tag'),
        ),
    ]
