# Generated by Django 4.1 on 2023-02-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mini_image',
            field=models.ImageField(default='', upload_to='photos/blog/mini_images', verbose_name='Міні фото до посту'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='photos/blog/images', verbose_name='Фото до посту'),
        ),
    ]
