# Generated by Django 4.1 on 2023-03-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogcategory_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(help_text='заповнюється автоматично, коли вносишь назву', max_length=100, unique=True, verbose_name='написання в URL'),
        ),
    ]
