# Generated by Django 4.1 on 2023-02-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_mini_image_alter_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mini_image',
            field=models.ImageField(upload_to='photos/blog/mini_images', verbose_name='Міні фото до посту'),
        ),
    ]
