# Generated by Django 4.1 on 2023-03-09 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_related_posts_post_related_posts_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_date',), 'verbose_name': 'пост', 'verbose_name_plural': 'пости'},
        ),
    ]
