# Generated by Django 4.1 on 2023-03-10 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_comment_postcomment_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
