# Generated by Django 4.1 on 2023-03-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='URL переходу'),
        ),
    ]
