# Generated by Django 4.1 on 2023-03-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_banner_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ('-modified_date',), 'verbose_name': 'коментар', 'verbose_name_plural': 'коментари'},
        ),
        migrations.AlterField(
            model_name='post',
            name='banner_url',
            field=models.URLField(blank=True, help_text='Введіть URL куди переходити по кліку на головне фото поста', max_length=255, verbose_name='URL переходу'),
        ),
    ]
