# Generated by Django 4.1 on 2023-03-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_token', models.CharField(max_length=100, verbose_name='токен')),
                ('tg_chat', models.CharField(max_length=100, verbose_name='чат ID')),
                ('tg_api', models.CharField(max_length=100, verbose_name='API адреса')),
                ('tg_message', models.TextField(blank=True, verbose_name='текст повідомлення')),
                ('available', models.BooleanField(default=True, verbose_name='активний')),
            ],
            options={
                'verbose_name_plural': 'налаштування',
            },
        ),
    ]
