# Generated by Django 4.1 on 2023-03-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramsettings',
            options={'verbose_name_plural': 'налаштування'},
        ),
        migrations.AlterField(
            model_name='telegramsettings',
            name='available',
            field=models.BooleanField(default=True, verbose_name='активний'),
        ),
        migrations.AlterField(
            model_name='telegramsettings',
            name='tg_chat',
            field=models.CharField(max_length=100, verbose_name='чат ID'),
        ),
        migrations.AlterField(
            model_name='telegramsettings',
            name='tg_message',
            field=models.TextField(blank=True, verbose_name='текст повідомлення'),
        ),
        migrations.AlterField(
            model_name='telegramsettings',
            name='tg_token',
            field=models.CharField(max_length=100, verbose_name='токен'),
        ),
    ]
