# Generated by Django 4.1 on 2023-03-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='заголовок')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='опис')),
                ('image', models.ImageField(blank=True, upload_to='photos/benefits', verbose_name='фото переваги')),
            ],
            options={
                'verbose_name': 'перевагу',
                'verbose_name_plural': 'переваги',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='найменування партнеру')),
                ('image', models.ImageField(blank=True, upload_to='photos/partners', verbose_name='фото партнера')),
            ],
            options={
                'verbose_name': 'партнер',
                'verbose_name_plural': 'партнери',
            },
        ),
    ]
