# Generated by Django 4.1 on 2023-03-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='найменування партнера'),
        ),
    ]
