# Generated by Django 4.1 on 2023-03-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benefits', '0002_alter_benefits_options_alter_partners_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefits',
            options={'verbose_name': 'перевагу', 'verbose_name_plural': 'переваги'},
        ),
    ]
