# Generated by Django 4.1 on 2023-03-22 05:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='ПІБ')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=16, region=None, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='телефон')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('note', models.TextField(blank=True, verbose_name='примітка')),
            ],
            options={
                'verbose_name': 'покупця',
                'verbose_name_plural': 'покупці',
                'ordering': ('customer_name',),
            },
        ),
        migrations.CreateModel(
            name='NewPostTerminals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('terminal', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('city',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, verbose_name='номер замовлення')),
                ('customer_name', models.CharField(max_length=100, verbose_name='ПІБ')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=16, region=None, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='телефон')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('city', models.CharField(max_length=50, verbose_name='місто')),
                ('street', models.CharField(max_length=50, verbose_name='вулиця')),
                ('house', models.CharField(max_length=10, verbose_name='будинок')),
                ('room', models.CharField(blank=True, max_length=10, verbose_name='квартира')),
                ('new_post_city', models.CharField(default='-', max_length=100, verbose_name='Місто Нової Пошти')),
                ('new_post_office', models.CharField(default='-', max_length=200, verbose_name='Відділення Нової Пошти')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='бажана дата доставки')),
                ('delivery_time', models.TimeField(blank=True, null=True, verbose_name='час доставки')),
                ('delivery_method', models.CharField(choices=[('COURIER_CHERKASY', "Кур'єр по м. Черкаси"), ('COURIER_ZOLOTONOSHA', "Кур'єр по м. Золотоноша"), ('DELIVERY COMPANY', 'Доставка Новою Поштою')], default='COURIER_CHERKASY', max_length=50, verbose_name='спосіб доставки')),
                ('payment_method', models.CharField(choices=[('CASH', 'Готівка'), ('TERMINAL', "Кур'єру через термінал"), ('VISA', 'Оплата карткою VISA/MasterCard')], default='CASH', max_length=50, verbose_name='спосіб оплати')),
                ('order_note', models.TextField(blank=True, max_length=255, verbose_name='примітка до замовлення')),
                ('order_total', models.IntegerField(verbose_name='усього зі знижкою')),
                ('discount', models.IntegerField(verbose_name='знижка')),
                ('ip', models.CharField(blank=True, max_length=20, verbose_name='IP адреса')),
                ('is_ordered', models.BooleanField(default=False, verbose_name='замовлено')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата замовлення')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='дата коригування')),
            ],
            options={
                'verbose_name': 'замовлення',
                'verbose_name_plural': 'замовлення',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_1', models.TextField(blank=True, help_text='повідомлення між привітанням та деталями замовлення', verbose_name='текст до деталей замовлення')),
                ('text_2', models.TextField(blank=True, help_text='повідомлення після деталей замовлення', verbose_name='текст після деталей замовлення')),
            ],
            options={
                'verbose_name': 'повідомлення покупцям',
                'verbose_name_plural': 'повідомлення на email',
            },
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'підписчика',
                'verbose_name_plural': 'підписчики',
            },
        ),
        migrations.CreateModel(
            name='ThanksPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='текст до сторінки подяки')),
            ],
            options={
                'verbose_name': 'сторінка подяки',
                'verbose_name_plural': 'сторінка подяки',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='ціна товару')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='кількість')),
                ('is_ordered', models.BooleanField(default=False, verbose_name='замовлено')),
                ('user_email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата створення')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='дата оновлення')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='замовлення')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'товар в замовленні',
                'verbose_name_plural': 'товари в замовленні',
                'ordering': ('-created',),
            },
        ),
    ]
