# Generated by Django 4.1 on 2023-02-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='new_post_city',
        ),
    ]
