# Generated by Django 4.1 on 2023-02-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.IntegerField(verbose_name='Усього зі знижкою'),
        ),
    ]
