# Generated by Django 4.1 on 2023-02-22 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_newpostterminals_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newpostterminals',
            options={'ordering': ('city',)},
        ),
    ]
