# Generated by Django 4.1 on 2023-02-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_new_post_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='new_post_city',
            field=models.CharField(default='', max_length=50, verbose_name='Місто Нової Пошти'),
        ),
    ]
