# Generated by Django 4.1 on 2023-02-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_customers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'ordering': ('customer_name',)},
        ),
        migrations.AddField(
            model_name='customers',
            name='note',
            field=models.TextField(blank=True, verbose_name='Примітка'),
        ),
    ]
