# Generated by Django 4.1 on 2023-02-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_new_post_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_note',
            field=models.TextField(blank=True, max_length=255, verbose_name='Примітка до замовлення'),
        ),
    ]
