# Generated by Django 4.1 on 2023-02-28 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_customers_options_customers_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'ordering': ('customer_name',), 'verbose_name_plural': 'Покупці'},
        ),
    ]
