# Generated by Django 4.1 on 2023-02-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='new_post_office',
            field=models.CharField(max_length=255, verbose_name='Відділення Нової Пошти'),
        ),
    ]
