# Generated by Django 4.1 on 2023-03-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_subscribers_alter_customers_email_alter_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('COURIER_CHERKASY', "Кур'єр по м. Черкаси"), ('COURIER_ZOLOTONOSHA', "Кур'єр по м. Золотоноша"), ('DELIVERY COMPANY', 'Доставка Новою Поштою')], default='COURIER_CHERKASY', max_length=50, verbose_name='Спосіб доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Готівка'), ('TERMINAL', "Кур'єру через термінал"), ('VISA', 'Оплата карткою VISA/MasterCard')], default='CASH', max_length=50, verbose_name='Спосіб оплати'),
        ),
    ]
