# Generated by Django 4.1 on 2023-03-06 13:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productinfo'),
        ('orders', '0007_alter_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_1', models.TextField(blank=True, help_text='повідомлення між привітанням та деталями замовлення', verbose_name='текст до деталей замовлення')),
                ('text_2', models.TextField(blank=True, help_text='повідомлення після деталей замовлення', verbose_name='текст після деталей замовлення')),
            ],
            options={
                'verbose_name': 'Повідомлення покупцям',
                'verbose_name_plural': 'Повідомлення покупцям',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'ordering': ('customer_name',), 'verbose_name_plural': 'покупці'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'замовлення', 'verbose_name_plural': 'замовлення'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('-created',), 'verbose_name': 'товар в замовленні', 'verbose_name_plural': 'товари в замовленні'},
        ),
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name_plural': 'підписки'},
        ),
        migrations.AlterField(
            model_name='customers',
            name='note',
            field=models.TextField(blank=True, verbose_name='примітка'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=16, region=None, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='newpostterminals',
            name='terminal',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=50, verbose_name='місто'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата створення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='бажана дата доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('COURIER_CHERKASY', "Кур'єр по м. Черкаси"), ('COURIER_ZOLOTONOSHA', "Кур'єр по м. Золотоноша"), ('DELIVERY COMPANY', 'Доставка Новою Поштою')], default='COURIER_CHERKASY', max_length=50, verbose_name='спосіб доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True, verbose_name='бажаний час доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.IntegerField(verbose_name='знижка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='house',
            field=models.CharField(max_length=10, verbose_name='будинок'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='замовлено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_note',
            field=models.TextField(blank=True, max_length=255, verbose_name='примітка до замовлення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=20, verbose_name='номер замовлення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.IntegerField(verbose_name='усього зі знижкою'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Готівка'), ('TERMINAL', "Кур'єру через термінал"), ('VISA', 'Оплата карткою VISA/MasterCard')], default='CASH', max_length=50, verbose_name='спосіб оплати'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=16, region=None, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='room',
            field=models.CharField(blank=True, max_length=10, verbose_name='квартира'),
        ),
        migrations.AlterField(
            model_name='order',
            name='street',
            field=models.CharField(max_length=50, verbose_name='вулиця'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='дата оновлення'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата створення'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='замовлено'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='замовлення'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(verbose_name='ціна товару'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='кількість'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='дата оновлення'),
        ),
    ]
