# Generated by Django 4.1 on 2023-03-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_ordermessage_alter_customers_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='ordermessage',
            managers=[
            ],
        ),
    ]
