# Generated by Django 4.1 on 2023-02-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_communication_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='communication_method',
            field=models.CharField(blank=True, choices=[('PHONE', 'Телефон'), ('TELEGRAM', 'Telegram'), ('VIBER', 'Viber')], default='PHONE', max_length=20, verbose_name='Спосіб оплати'),
        ),
    ]
