# Generated by Django 4.1 on 2023-03-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_delivery_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThanksPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='текст до сторінки подяки')),
            ],
            options={
                'verbose_name': 'сторінку подяки',
                'verbose_name_plural': 'сторінка подяки',
            },
        ),
    ]
