# Generated by Django 4.1 on 2023-03-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_thankspage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'ordering': ('customer_name',), 'verbose_name': 'покупця', 'verbose_name_plural': 'покупці'},
        ),
        migrations.AlterModelOptions(
            name='ordermessage',
            options={'verbose_name': 'повідомлення покупцям', 'verbose_name_plural': 'повідомлення на email'},
        ),
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'підписчика', 'verbose_name_plural': 'підписчики'},
        ),
        migrations.AlterModelOptions(
            name='thankspage',
            options={'verbose_name': 'сторінка подяки', 'verbose_name_plural': 'сторінка подяки'},
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата замовлення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='дата коригування'),
        ),
    ]
