# Generated by Django 4.1 on 2023-02-15 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_communication_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='communication_method',
        ),
    ]
