# Generated by Django 4.1 on 2023-02-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_order_communication_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='new_post_city',
            field=models.CharField(max_length=100, verbose_name='Місто Нової Пошти'),
        ),
        migrations.AlterField(
            model_name='order',
            name='new_post_office',
            field=models.CharField(max_length=200, verbose_name='Відділення Нової Пошти'),
        ),
    ]
