# Generated by Django 4.1 on 2023-03-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_customers_options_alter_ordermessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='user_email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='E-mail'),
        ),
    ]
