# Generated by Django 4.1 on 2023-03-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderitem_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='user_email',
            field=models.EmailField(max_length=100, verbose_name='E-mail'),
        ),
    ]
