# Generated by Django 4.1 on 2023-02-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_new_post_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPostTerminals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('terminal', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('city', 'terminal'),
            },
        ),
    ]
