# Generated by Django 4.1 on 2023-03-22 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='назва блоку')),
            ],
            options={
                'verbose_name': 'блок',
                'verbose_name_plural': 'блоки',
            },
        ),
        migrations.CreateModel(
            name='NewProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_prod1_active', models.ImageField(upload_to='photos/new_products', verbose_name='фото 1 (активне)')),
                ('image_prod1', models.ImageField(upload_to='photos/new_products', verbose_name='фото 2')),
                ('image_prod2_active', models.ImageField(upload_to='photos/new_products', verbose_name='фото 1 (активне)')),
                ('image_prod2', models.ImageField(upload_to='photos/new_products', verbose_name='фото 2')),
                ('product_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_product_1', to='store.product', verbose_name='товар 1')),
                ('product_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_product_2', to='store.product', verbose_name='товар 2')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.blocktitle', verbose_name='назва блоку')),
            ],
            options={
                'verbose_name': 'новинка',
                'verbose_name_plural': 'новинки',
            },
        ),
        migrations.CreateModel(
            name='MostPopularRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_prod1_active', models.ImageField(upload_to='photos/popular_products', verbose_name='фото 1 (активне)')),
                ('image_prod1', models.ImageField(upload_to='photos/popular_products', verbose_name='фото 2')),
                ('image_prod2_active', models.ImageField(upload_to='photos/popular_products', verbose_name='фото 1 (активне)')),
                ('image_prod2', models.ImageField(upload_to='photos/popular_products', verbose_name='фото 2')),
                ('image_prod3_active', models.ImageField(upload_to='photos/popular_products', verbose_name='фото 1 (активне)')),
                ('image_prod3', models.ImageField(upload_to='photos/popular_products', verbose_name='фото 2')),
                ('product_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop_right_product_1', to='store.product', verbose_name='товар 1')),
                ('product_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop_right_product_2', to='store.product', verbose_name='товар 2')),
                ('product_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop_right_product_3', to='store.product', verbose_name='товар 3')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.blocktitle', verbose_name='назва блоку')),
            ],
            options={
                'verbose_name': 'популярний (праворуч)',
                'verbose_name_plural': 'популярні (праворуч)',
            },
        ),
        migrations.CreateModel(
            name='MostPopularLeft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_prod1_active', models.ImageField(upload_to='photos/popular_products', verbose_name='фото 1 (активне)')),
                ('image_prod1', models.ImageField(upload_to='photos/popular_products', verbose_name='фото 2')),
                ('image_prod2_active', models.ImageField(upload_to='photos/popular_products', verbose_name='фото 1 (активне)')),
                ('image_prod2', models.ImageField(upload_to='photos/popular_products', verbose_name='фото 2')),
                ('image_prod3_active', models.ImageField(upload_to='photos/popular_products', verbose_name='фото 1 (активне)')),
                ('image_prod3', models.ImageField(upload_to='photos/popular_products', verbose_name='фото 2')),
                ('product_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop_product_1', to='store.product', verbose_name='товар 1')),
                ('product_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop_product_2', to='store.product', verbose_name='товар 2')),
                ('product_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop_product_3', to='store.product', verbose_name='товар 3')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.blocktitle', verbose_name='назва блоку')),
            ],
            options={
                'verbose_name': 'популярний (ліворуч)',
                'verbose_name_plural': 'популярні (ліворуч)',
            },
        ),
        migrations.CreateModel(
            name='MostPopularCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_prod1_active', models.ImageField(upload_to='photos/popular_products', verbose_name='фото 1 (активне)')),
                ('image_prod1', models.ImageField(upload_to='photos/popular_products', verbose_name='фото 2')),
                ('image_prod2_active', models.ImageField(upload_to='photos/popular_products', verbose_name='фото 1 (активне)')),
                ('image_prod2', models.ImageField(upload_to='photos/popular_products', verbose_name='фото 2')),
                ('image_prod3_active', models.ImageField(upload_to='photos/popular_products', verbose_name='фото 1 (активне)')),
                ('image_prod3', models.ImageField(upload_to='photos/popular_products', verbose_name='фото 2')),
                ('product_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop_center_product_1', to='store.product', verbose_name='товар 1')),
                ('product_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop_center_product_2', to='store.product', verbose_name='товар 2')),
                ('product_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop_center_product_3', to='store.product', verbose_name='товар 3')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.blocktitle', verbose_name='назва блоку')),
            ],
            options={
                'verbose_name': 'популярний (по центру)',
                'verbose_name_plural': 'популярні (по центру)',
            },
        ),
        migrations.CreateModel(
            name='BestSellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_prod1_active', models.ImageField(upload_to='photos/bestsellers', verbose_name='фото 1 (активне)')),
                ('image_prod1', models.ImageField(upload_to='photos/bestsellers', verbose_name='фото 2')),
                ('image_prod2_active', models.ImageField(upload_to='photos/bestsellers', verbose_name='фото 1 (активне)')),
                ('image_prod2', models.ImageField(upload_to='photos/bestsellers', verbose_name='фото 2')),
                ('product_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_1', to='store.product', verbose_name='товар 1')),
                ('product_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_2', to='store.product', verbose_name='товар 2')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.blocktitle', verbose_name='назва блоку')),
            ],
            options={
                'verbose_name': 'бестселер',
                'verbose_name_plural': 'бестселери',
            },
        ),
    ]
