# Generated by Django 4.1 on 2023-03-07 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_product_slug'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bestsellers',
            options={'verbose_name': 'бестселер', 'verbose_name_plural': 'бестселери'},
        ),
        migrations.AlterModelOptions(
            name='blocktitle',
            options={'verbose_name': 'блок', 'verbose_name_plural': 'блоки'},
        ),
        migrations.AlterModelOptions(
            name='mostpopularcenter',
            options={'verbose_name': 'популярний (по центру)', 'verbose_name_plural': 'популярні (по центру)'},
        ),
        migrations.AlterModelOptions(
            name='mostpopularleft',
            options={'verbose_name': 'популярний (ліворуч)', 'verbose_name_plural': 'популярні (ліворуч)'},
        ),
        migrations.AlterModelOptions(
            name='mostpopularright',
            options={'verbose_name': 'популярний (праворуч)', 'verbose_name_plural': 'популярні (праворуч)'},
        ),
        migrations.AlterModelOptions(
            name='newproducts',
            options={'verbose_name': 'новинка', 'verbose_name_plural': 'новинки'},
        ),
        migrations.AlterField(
            model_name='bestsellers',
            name='image_prod1',
            field=models.ImageField(upload_to='photos/bestsellers', verbose_name='фото 2'),
        ),
        migrations.AlterField(
            model_name='bestsellers',
            name='image_prod1_active',
            field=models.ImageField(upload_to='photos/bestsellers', verbose_name='фото 1 (активне)'),
        ),
        migrations.AlterField(
            model_name='bestsellers',
            name='image_prod2',
            field=models.ImageField(upload_to='photos/bestsellers', verbose_name='фото 2'),
        ),
        migrations.AlterField(
            model_name='bestsellers',
            name='image_prod2_active',
            field=models.ImageField(upload_to='photos/bestsellers', verbose_name='фото 1 (активне)'),
        ),
        migrations.AlterField(
            model_name='bestsellers',
            name='product_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_1', to='store.product', verbose_name='товар 1'),
        ),
        migrations.AlterField(
            model_name='bestsellers',
            name='product_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_2', to='store.product', verbose_name='товар 2'),
        ),
        migrations.AlterField(
            model_name='bestsellers',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.blocktitle', verbose_name='назва блоку'),
        ),
        migrations.AlterField(
            model_name='blocktitle',
            name='title',
            field=models.CharField(max_length=100, verbose_name='назва блоку'),
        ),
        migrations.AlterField(
            model_name='mostpopularcenter',
            name='image_prod1',
            field=models.ImageField(upload_to='photos/popular_products', verbose_name='фото 2'),
        ),
        migrations.AlterField(
            model_name='mostpopularcenter',
            name='image_prod1_active',
            field=models.ImageField(upload_to='photos/popular_products', verbose_name='фото 1 (активне)'),
        ),
        migrations.AlterField(
            model_name='mostpopularcenter',
            name='image_prod2',
            field=models.ImageField(upload_to='photos/popular_products', verbose_name='фото 2'),
        ),
        migrations.AlterField(
            model_name='mostpopularcenter',
            name='image_prod2_active',
            field=models.ImageField(upload_to='photos/popular_products', verbose_name='фото 1 (активне)'),
        ),
        migrations.AlterField(
            model_name='mostpopularcenter',
            name='image_prod3',
            field=models.ImageField(upload_to='photos/popular_products', verbose_name='фото 2'),
        ),
        migrations.AlterField(
            model_name='mostpopularcenter',
            name='image_prod3_active',
            field=models.ImageField(upload_to='photos/popular_products', verbose_name='фото 1 (активне)'),
        ),
        migrations.AlterField(
            model_name='mostpopularcenter',
            name='product_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop_center_product_1', to='store.product', verbose_name='товар 1'),
        ),
        migrations.AlterField(
            model_name='mostpopularcenter',
            name='product_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop_center_product_2', to='store.product', verbose_name='товар 2'),
        ),
        migrations.AlterField(
            model_name='mostpopularcenter',
            name='product_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop_center_product_3', to='store.product', verbose_name='товар 3'),
        ),
        migrations.AlterField(
            model_name='mostpopularcenter',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.blocktitle', verbose_name='назва блоку'),
        ),
        migrations.AlterField(
            model_name='mostpopularleft',
            name='image_prod1',
            field=models.ImageField(upload_to='photos/popular_products', verbose_name='фото 2'),
        ),
        migrations.AlterField(
            model_name='mostpopularleft',
            name='image_prod1_active',
            field=models.ImageField(upload_to='photos/popular_products', verbose_name='фото 1 (активне)'),
        ),
        migrations.AlterField(
            model_name='mostpopularleft',
            name='image_prod2',
            field=models.ImageField(upload_to='photos/popular_products', verbose_name='фото 2'),
        ),
        migrations.AlterField(
            model_name='mostpopularleft',
            name='image_prod2_active',
            field=models.ImageField(upload_to='photos/popular_products', verbose_name='фото 1 (активне)'),
        ),
        migrations.AlterField(
            model_name='mostpopularleft',
            name='image_prod3',
            field=models.ImageField(upload_to='photos/popular_products', verbose_name='фото 2'),
        ),
        migrations.AlterField(
            model_name='mostpopularleft',
            name='image_prod3_active',
            field=models.ImageField(upload_to='photos/popular_products', verbose_name='фото 1 (активне)'),
        ),
        migrations.AlterField(
            model_name='mostpopularleft',
            name='product_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop_product_1', to='store.product', verbose_name='товар 1'),
        ),
        migrations.AlterField(
            model_name='mostpopularleft',
            name='product_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop_product_2', to='store.product', verbose_name='товар 2'),
        ),
        migrations.AlterField(
            model_name='mostpopularleft',
            name='product_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop_product_3', to='store.product', verbose_name='товар 3'),
        ),
        migrations.AlterField(
            model_name='mostpopularleft',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.blocktitle', verbose_name='назва блоку'),
        ),
        migrations.AlterField(
            model_name='mostpopularright',
            name='image_prod1',
            field=models.ImageField(upload_to='photos/popular_products', verbose_name='фото 2'),
        ),
        migrations.AlterField(
            model_name='mostpopularright',
            name='image_prod1_active',
            field=models.ImageField(upload_to='photos/popular_products', verbose_name='фото 1 (активне)'),
        ),
        migrations.AlterField(
            model_name='mostpopularright',
            name='image_prod2',
            field=models.ImageField(upload_to='photos/popular_products', verbose_name='фото 2'),
        ),
        migrations.AlterField(
            model_name='mostpopularright',
            name='image_prod2_active',
            field=models.ImageField(upload_to='photos/popular_products', verbose_name='фото 1 (активне)'),
        ),
        migrations.AlterField(
            model_name='mostpopularright',
            name='image_prod3',
            field=models.ImageField(upload_to='photos/popular_products', verbose_name='фото 2'),
        ),
        migrations.AlterField(
            model_name='mostpopularright',
            name='image_prod3_active',
            field=models.ImageField(upload_to='photos/popular_products', verbose_name='фото 1 (активне)'),
        ),
        migrations.AlterField(
            model_name='mostpopularright',
            name='product_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop_right_product_1', to='store.product', verbose_name='товар 1'),
        ),
        migrations.AlterField(
            model_name='mostpopularright',
            name='product_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop_right_product_2', to='store.product', verbose_name='товар 2'),
        ),
        migrations.AlterField(
            model_name='mostpopularright',
            name='product_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop_right_product_3', to='store.product', verbose_name='товар 3'),
        ),
        migrations.AlterField(
            model_name='mostpopularright',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.blocktitle', verbose_name='назва блоку'),
        ),
        migrations.AlterField(
            model_name='newproducts',
            name='image_prod1',
            field=models.ImageField(upload_to='photos/new_products', verbose_name='фото 2'),
        ),
        migrations.AlterField(
            model_name='newproducts',
            name='image_prod1_active',
            field=models.ImageField(upload_to='photos/new_products', verbose_name='фото 1 (активне)'),
        ),
        migrations.AlterField(
            model_name='newproducts',
            name='image_prod2',
            field=models.ImageField(upload_to='photos/new_products', verbose_name='фото 2'),
        ),
        migrations.AlterField(
            model_name='newproducts',
            name='image_prod2_active',
            field=models.ImageField(upload_to='photos/new_products', verbose_name='фото 1 (активне)'),
        ),
        migrations.AlterField(
            model_name='newproducts',
            name='product_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_product_1', to='store.product', verbose_name='товар 1'),
        ),
        migrations.AlterField(
            model_name='newproducts',
            name='product_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_product_2', to='store.product', verbose_name='товар 2'),
        ),
        migrations.AlterField(
            model_name='newproducts',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.blocktitle', verbose_name='назва блоку'),
        ),
    ]
