# Generated by Django 4.1 on 2023-01-26 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_is_active_product_is_new_and_more'),
        ('sales', '0002_alter_bestsellers_image_prod1_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocktitle',
            options={'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
        migrations.CreateModel(
            name='NewProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_prod1_active', models.ImageField(upload_to='photos/new_products', verbose_name='Фото 1 (активне)')),
                ('image_prod1', models.ImageField(upload_to='photos/new_products', verbose_name='Фото 2')),
                ('image_prod2_active', models.ImageField(upload_to='photos/new_products', verbose_name='Фото 1 (активне)')),
                ('image_prod2', models.ImageField(upload_to='photos/new_products', verbose_name='Фото 2')),
                ('product_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_product_1', to='store.product', verbose_name='Товар 1')),
                ('product_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_product_2', to='store.product', verbose_name='Товар 2')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.blocktitle', verbose_name='Назва блоку')),
            ],
            options={
                'verbose_name': 'Новинка',
                'verbose_name_plural': 'Новинки',
            },
        ),
    ]
