# Generated by Django 4.1 on 2023-01-26 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_is_active_product_is_new_and_more'),
        ('sales', '0004_mostpopularleft'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mostpopularleft',
            options={'verbose_name': 'Популярний (ліворуч)', 'verbose_name_plural': 'Популярні (ліворуч)'},
        ),
        migrations.AlterField(
            model_name='mostpopularleft',
            name='product_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop_product_3', to='store.product', verbose_name='Товар 3'),
        ),
        migrations.CreateModel(
            name='MostPopularRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_prod1_active', models.ImageField(upload_to='photos/popular_products', verbose_name='Фото 1 (активне)')),
                ('image_prod1', models.ImageField(upload_to='photos/popular_products', verbose_name='Фото 2')),
                ('image_prod2_active', models.ImageField(upload_to='photos/popular_products', verbose_name='Фото 1 (активне)')),
                ('image_prod2', models.ImageField(upload_to='photos/popular_products', verbose_name='Фото 2')),
                ('image_prod3_active', models.ImageField(upload_to='photos/popular_products', verbose_name='Фото 1 (активне)')),
                ('image_prod3', models.ImageField(upload_to='photos/popular_products', verbose_name='Фото 2')),
                ('product_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop_right_product_1', to='store.product', verbose_name='Товар 1')),
                ('product_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop_right_product_2', to='store.product', verbose_name='Товар 2')),
                ('product_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop_right_product_3', to='store.product', verbose_name='Товар 3')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.blocktitle', verbose_name='Назва блоку')),
            ],
            options={
                'verbose_name': 'Популярний (праворуч)',
                'verbose_name_plural': 'Популярні (праворуч)',
            },
        ),
        migrations.CreateModel(
            name='MostPopularCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_prod1_active', models.ImageField(upload_to='photos/popular_products', verbose_name='Фото 1 (активне)')),
                ('image_prod1', models.ImageField(upload_to='photos/popular_products', verbose_name='Фото 2')),
                ('image_prod2_active', models.ImageField(upload_to='photos/popular_products', verbose_name='Фото 1 (активне)')),
                ('image_prod2', models.ImageField(upload_to='photos/popular_products', verbose_name='Фото 2')),
                ('image_prod3_active', models.ImageField(upload_to='photos/popular_products', verbose_name='Фото 1 (активне)')),
                ('image_prod3', models.ImageField(upload_to='photos/popular_products', verbose_name='Фото 2')),
                ('product_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop_center_product_1', to='store.product', verbose_name='Товар 1')),
                ('product_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop_center_product_2', to='store.product', verbose_name='Товар 2')),
                ('product_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pop_center_product_3', to='store.product', verbose_name='Товар 3')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.blocktitle', verbose_name='Назва блоку')),
            ],
            options={
                'verbose_name': 'Популярний (по центру)',
                'verbose_name_plural': 'Популярні (по центру)',
            },
        ),
    ]
